### ISSUE TITLE
[wiki] Recipes, EditorSupport, and Tag-tweak

### ISSUE THREAD

**Issue by lcpichette** [CWood-sdf/banana.nvim#11]
## Issue

1. Syntax highlighting: I use neovim, and syntax highlighting for `nml` files was a little bit tricky to figure out -- but there's actually an incredibly clean and simple solution for it.
2. Getting started: In my experience getting started meant trying to understand the example in the README, getting a little bit confused, checking out the example and becoming even more confused until I wasn't. 

## Proposed Fix

1. EditorSupport.md file which outlines various tips and tricks to get `nml` file syntax highlighting for {x} editor. I've started it out with getting `nml` syntax highlighting with Neovim.
2. Recipes.md + pitfall hint for nml tag in Tag.md. Recipes.md is for storing solutions to various problems people might want to solve. I see it as a great way for those wanting to learn the plugin being able to do so with isolated chunks of logic. 

I tried to make the markdown files a copy + paste code block but there are code blocks within the files, so the syntax here just looks odd. 

I'll go ahead and provide the updated + new files below.

- [Tags.md](https://github.com/user-attachments/files/18270647/Tags.md)
- [EditorSupport.md](https://github.com/user-attachments/files/18270648/EditorSupport.md)
- [Recipes.md](https://github.com/user-attachments/files/18270649/Recipes.md)

**Comment by CWood-sdf** [comment]
Thanks for the suggestions!

For editor support, I completely overlooked that (mostly because I have had the setup stuff in my config for a few months now). I just committed some changes that should make that really easy. Now, users can just call the setup function (or `opts = ....` if using lazy.nvim) with the parameter `setupTs` which setups the treesitter parsers (but also loads nvim-treesitter)

so users can either (for lazy.nvim)

```lua
return {
  "CWood-sdf/banana.nvim",
  opts = {
    setupTs = false,
  }
}
-- then call require("banana").initTsParsers() in the nvim-treesitter setup
``` 

or

```lua
return {
  "CWood-sdf/banana.nvim",
  opts = {
    setupTs = true,
  }
}
```

**Comment by CWood-sdf** [comment]
If users want lsp support, then they can add nml as a supported filetype for the html lsp

if using nvim-lspconfig, that looks like:
```lua
require("lspconfig").html.setup({
   filetypes = { "html", "nml", "templ" }
   -- other configuration
})
```

though the plan is to eventually create my own fork of html lsp that can be guaranteed to only contain banana features

**Comment by CWood-sdf** [comment]
a recipes.md file is definitely a great idea.

I really like most of what you have in the attached markdown files, and I have also realized that there isnt much of a way to manage contributions on github wikis, so I will be adding a wiki folder to this repo so that you can add these wiki files to your pr

**Comment by lcpichette** [comment]
Thank you for creating the wiki folder so quickly! I went ahead and created a PR https://github.com/CWood-sdf/banana.nvim/pull/12 which references this issue. Going to close out this issue, any related conversation can be had there. I omitted the EditorSupport.md file from my PR as it sounds like you have a more official approach you've created (which is fantastic).

**Comment by CWood-sdf** [comment]
Also, there was a bug in setting the background files on nml and body tags to set the background on the entire buffer. I patched that earlier and thought I would let you know.

Now you can set the background on an entire window with either an `nml` or `body` selector:
```css
nml {
  hl-bg: red;
}
```
