### ISSUE TITLE
Luax support?

### ISSUE THREAD

**Issue by theKnightsOfRohan** [CWood-sdf/banana.nvim#2]
Kind of like how jsx can inline html and return it from a function, are there any plans in the future to support that in a "luax" file type with this plugin?

**Comment by CWood-sdf** [comment]
Currently there are no plans for a luax file type for a few reasons:

- lsp support probably would probably be rough because I would have to translate the entire file into lua, with luals running under the hood (probably a separate process from the main luals)
- The markup has to be compiled once (this is mostly a self imposed requirement on the entire project), but this does not really work well with banana currently. This leaves the other option to compile it into a lua table tree which would probably be separate from the main renderable tree
- This would probably add a lot of complexity from reactivity and stuff (think of all the use... functions in react)

This does not mean that luax or something similar will not happen, but it will probably be, at the earliest, a few months away. In the meantime, I will try my best to make templating a very valid option because that does not add as large an overhead as a luax format
