### ISSUE TITLE
[Question] Any way to support listening/accepting inputs?

### ISSUE THREAD

**Issue by lcpichette** [CWood-sdf/banana.nvim#9]
Hello!

Able to get the plugin working, visualizing a colored buffer with text.

I'd like to accept text input and listen to changes to this text input.

I don't see an [element](https://github.com/CWood-sdf/banana.nvim/wiki/Tags) or an [event listener](https://github.com/CWood-sdf/banana.nvim/wiki/Ast#event-handlers) for this.

The only tag I saw as a possibility was `slot`, but `slot` doesn't seem to be an equivalent for `input` -- rather, more of a way of passing elements/tags in a dynamic way into a template. 

Thank you for your time and assistance : )

**Comment by CWood-sdf** [comment]
If I am understanding correctly, you are looking for an <input> element. Unfortunately, as of now, there is currently no native <input> element. You could probably cobble together a component using the InsertEnter and TextChanged autocmds, ast:isHovering(), and some bounds checking but it would probably be very hacky and currently there is no public api for getting bounds (getBoundingBox() should be coming soon though). 

The two ways to best do this as of now are either to use a prompt buffer or add a keymap using ast:attachRemap that calls vim.fn.input() when it is activated. 

I dont think <input> support will come for a while (if ever) just because there are so many possibilities to modify a line that properly validating input while also ensuring the rest of the buffer is untouched until the next render cycle would be very difficult. I would happily look into creating an input element if that is what you want, but there are no guarantees on whether I would be able to create something that works well enough to be put in the library

**Comment by lcpichette** [comment]
Hey CWood, you're right on the money -- I am looking for an element that functions similarly to `vim.fn.input`. 

Hacking together banana buffers and native buffers shouldn't be an issue, but that limits the benefit of using banana as now the native buffers can't benefit from the stylistic boons that banana buffers have. The easiest, and to me the option that leverages banana the best, would indeed be a combination of something like `InsertEnter and TextChanged autocmds, ast:isHovering()` (as you had mentioned). 

If you ever have an Ah-ha moment for a kind of "input" element then I think that'd be huge for those wanting to make the following kind of plugins:
- to-do
- quick notes
- labeled marks
- file name/content searching (fzf-lua, telescope)
- plugin installer (search by name/author)
- etc

I definitely understand it being a lower priority, I read your README and I agree with you that more general-purpose functionality should be supported first before tackling support for these kinds of cases.

I really appreciate the work you've been doing on this plugin!! I'll try to hack something together and let you know any pain points. Maybe I'll learn enough about banana in the process to be able to contribute to the docs : )

**Comment by CWood-sdf** [comment]
yea, you could try to do something like 

```lua
local el = document:getElementById("input")
el:attachRemap("n", "<CR>", { "hover" }, function()
    local in = vim.fn.input("Input text: ")
    el:setTextContent(in)
end, {})
```

if you want something super simple
